namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      any-custom: value
      # All labels on Rancher clusters are available using global.fleet.clusterLabels.LABELNAME
      # These can now be accessed directly as variables
      variableName: global.fleet.clusterLabels.LABELNAME
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      any-custom: value
      # All labels on Rancher clusters are available using global.fleet.clusterLabels.LABELNAME
      # These can now be accessed directly as variables
      variableName: global.fleet.clusterLabels.LABELNAME
      replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      any-custom: value
      # All labels on Rancher clusters are available using global.fleet.clusterLabels.LABELNAME
      # These can now be accessed directly as variables
      variableName: global.fleet.clusterLabels.LABELNAME
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod