namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      global:
        fleet:
          clusterLabels: {"test123": "test456"}
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      global:
        fleet:
          clusterLabels: {"test456": "test789"}
      replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      global:
        fleet:
          clusterLabels: {"test789": "test123"}
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
