namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      global:
        fleet:
          clusterLabels: {}
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      global:
        fleet:
          clusterLabels: {}
      replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      global:
        fleet:
          clusterLabels: {}
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod